name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev
            
    - name: Install Buildozer
      run: pip install buildozer Cython==0.29.33
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: cat-game-apk
        path: bin/*.apk
